name: endernote
description: "Your versatile note-taking companion. Craft, create, and unleash your ideas with ease!"

version: 4.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.3
  flutter_bloc: ^9.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  bloc: ^9.0.0
  path: ^1.9.0
  flutter_speed_dial: ^7.0.0
  iconsax_linear: ^1.1.0
  shared_preferences: ^2.5.3
  file_picker: ^10.3.3
  hive_flutter: ^1.1.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: SourceSans3Regular
      fonts:
      - asset: lib/assets/SourceSans3-Regular.ttf
    - family: SourceSans3Light
      fonts:
        - asset: lib/assets/SourceSans3-Light.ttf
    - family: SourceSans3Bold
      fonts:
        - asset: lib/assets/SourceSans3-Bold.ttf
    - family: WorkSans
      fonts:
        - asset: lib/assets/WorkSans.ttf
    - family: RobotoSlab
      fonts:
        - asset: lib/assets/RobotoSlab.ttf
    - family: JetBrainsMono
      fonts:
        - asset: lib/assets/JetBrainsMono.ttf
