name: endernote
description: "Your versatile note-taking companion. Craft, create, and unleash your ideas with ease!"

version: 2.3.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.3
  ficonsax: ^0.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  bloc: ^8.1.4
  path: ^1.9.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: FiraCode
      fonts:
        - asset: lib/assets/FiraCode.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: lib/assets/PlayfairDisplay.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/Roboto.ttf
